MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: "/data5/liyuke/checkpoint/jx_vit_base_p16_224-80ecf9dd.pth" # root of pretrain path
  METRIC_LOSS_TYPE: 'triplet_center' # triplet, triplet_center
  DIM: 768
  IF_LABELSMOOTH: 'on'
  NAME: 'vit'
  NO_MARGIN: True
  DEVICE_ID: ('8')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: 12
  DROP_PATH: 0.1

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  REA:
    ENABLED: True

DATASETS:
  TRAIN: ('UAVHuman',)
  TEST: ('UAVHuman',)
  ROOT_DIR: ('/data5/liyuke') # root of datasets

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 60
  BASE_LR: 0.01
  IMS_PER_BATCH: 64
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 60
  EVAL_PERIOD: 5
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  SEED: 1234

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: True
  WEIGHT: ''
  QUERY_AGGREGATE: True
  NECK_FEAT: 'before'
  FEAT_NORM: True
  ATTRIBUTE_RECOGNITION: False

LOG_ROOT: '/data5/liyuke/exp/' # root of log file
TB_LOG_ROOT: './tb_log/'

LOG_NAME: ''
